export const REQUEST_ARTICLES = "REQUEST_ARTICLES";
export const RECEIVE_ARTICLES = "RECEIVE_ARTICLES";
export const SELECT_ARTICLE = "SELECT_ARTICLE";
export const INVALIDATE_ARTICLE = "INVALIDATE_ARTICLE";
export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_REGISTER = "REQUEST_REGISTER";
export const REQUEST_TAGS = "REQUEST_TAGS";
export const FETCH_USER = "FETCH_USER";
